name: "Aduro2MQTT"
slug: "aduro2mqtt"
version: "1.0.4"
description: "Bridge zwischen Aduro Pellet-Ofen (NBE-UDP) und MQTT"
url: "https://github.com/vothmarkus/Aduro2mqttAddon"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: application
init: false
stage: stable
ingress: false
host_network: false

map:
  - type: addon_config
  - type: share

options:
  mqtt_host: null
  mqtt_port: 1883
  mqtt_client_id: "aduro2mqtt"
  mqtt_user: null
  mqtt_password: null
  mqtt_base_topic: "aduro2mqtt"

  aduro_host: null
  aduro_serial: null
  aduro_pin: null
  aduro_poll_interval: 30

  log_level: "INFO"

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_client_id: str
  mqtt_user: "str?"
  mqtt_password: "password?"
  mqtt_base_topic: str

  aduro_host: str
  aduro_serial: str
  aduro_pin: str
  aduro_poll_interval: int

  log_level: list(WARNING|INFO|DEBUG)
