name: Aduro2MQTT
version: 1.4.8
slug: aduro2mqtt
description: "MQTT bridge for Aduro H2 with Home Assistant Discovery."
arch:
  - amd64
startup: application
boot: auto
init: false
ports: {}
map: []
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_client_id: "aduro2mqtt"
  mqtt_user: ""
  mqtt_password: ""
  mqtt_base_topic: "aduro2mqtt"
  aduro_host: ""
  aduro_serial: ""
  aduro_pin: ""
  aduro_poll_interval: 30
  discovery_enable: true
  discovery_prefix: "homeassistant"
  device_name: "Aduro H2"
  device_id: "aduro_h2"
  discovery_exclude:
    - boiler_pump_state
    - return_temp
  log_level: "INFO"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_client_id: str
  mqtt_user: str
  mqtt_password: str
  mqtt_base_topic: str
  aduro_host: str
  aduro_serial: str
  aduro_pin: str
  aduro_poll_interval: int
  discovery_enable: bool
  discovery_prefix: str
  device_name: str
  device_id: str
  discovery_exclude:
    - str
  log_level: list(INFO|DEBUG|WARNING)
